version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
    command: crystal run src/main.cr
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 3001:3001
    command: mongod --smallfiles --logpath=/dev/null
